// Fuzz testing: 100+ same-sized blocks, randomly added and removed

#include "testharness.h"

const char *mytest(allocator *a) {
  void *v1 = a->malloc(3*sizeof(void *));
  void *v2 = a->malloc(3*sizeof(void *));
  a->free(v2);
  a->free(v1);
  void *v3 = a->malloc(3*sizeof(void *));
  void *v4 = a->malloc(3*sizeof(void *));
  a->free(v3);
  void *v5 = a->malloc(3*sizeof(void *));
  void *v6 = a->malloc(3*sizeof(void *));
  void *v7 = a->malloc(3*sizeof(void *));
  a->free(v4);
  void *v8 = a->malloc(3*sizeof(void *));
  void *v9 = a->malloc(3*sizeof(void *));
  a->free(v7);
  void *v10 = a->malloc(3*sizeof(void *));
  void *v11 = a->malloc(3*sizeof(void *));
  a->free(v11);
  void *v12 = a->malloc(3*sizeof(void *));
  a->free(v10);
  void *v13 = a->malloc(3*sizeof(void *));
  void *v14 = a->malloc(3*sizeof(void *));
  a->free(v13);
  a->free(v5);
  void *v15 = a->malloc(3*sizeof(void *));
  void *v16 = a->malloc(3*sizeof(void *));
  void *v17 = a->malloc(3*sizeof(void *));
  a->free(v6);
  void *v18 = a->malloc(3*sizeof(void *));
  void *v19 = a->malloc(3*sizeof(void *));
  a->free(v9);
  void *v20 = a->malloc(3*sizeof(void *));
  void *v21 = a->malloc(3*sizeof(void *));
  void *v22 = a->malloc(3*sizeof(void *));
  void *v23 = a->malloc(3*sizeof(void *));
  void *v24 = a->malloc(3*sizeof(void *));
  void *v25 = a->malloc(3*sizeof(void *));
  void *v26 = a->malloc(3*sizeof(void *));
  a->free(v24);
  void *v27 = a->malloc(3*sizeof(void *));
  void *v28 = a->malloc(3*sizeof(void *));
  a->free(v26);
  void *v29 = a->malloc(3*sizeof(void *));
  void *v30 = a->malloc(3*sizeof(void *));
  a->free(v23);
  void *v31 = a->malloc(3*sizeof(void *));
  void *v32 = a->malloc(3*sizeof(void *));
  void *v33 = a->malloc(3*sizeof(void *));
  void *v34 = a->malloc(3*sizeof(void *));
  a->free(v22);
  void *v35 = a->malloc(3*sizeof(void *));
  void *v36 = a->malloc(3*sizeof(void *));
  void *v37 = a->malloc(3*sizeof(void *));
  a->free(v28);
  a->free(v30);
  void *v38 = a->malloc(3*sizeof(void *));
  a->free(v18);
  void *v39 = a->malloc(3*sizeof(void *));
  void *v40 = a->malloc(3*sizeof(void *));
  void *v41 = a->malloc(3*sizeof(void *));
  a->free(v31);
  void *v42 = a->malloc(3*sizeof(void *));
  void *v43 = a->malloc(3*sizeof(void *));
  void *v44 = a->malloc(3*sizeof(void *));
  void *v45 = a->malloc(3*sizeof(void *));
  void *v46 = a->malloc(3*sizeof(void *));
  a->free(v39);
  void *v47 = a->malloc(3*sizeof(void *));
  a->free(v44);
  void *v48 = a->malloc(3*sizeof(void *));
  void *v49 = a->malloc(3*sizeof(void *));
  a->free(v41);
  void *v50 = a->malloc(3*sizeof(void *));
  void *v51 = a->malloc(3*sizeof(void *));
  void *v52 = a->malloc(3*sizeof(void *));
  a->free(v42);
  void *v53 = a->malloc(3*sizeof(void *));
  void *v54 = a->malloc(3*sizeof(void *));
  void *v55 = a->malloc(3*sizeof(void *));
  a->free(v37);
  void *v56 = a->malloc(3*sizeof(void *));
  a->free(v53);
  a->free(v27);
  void *v57 = a->malloc(3*sizeof(void *));
  void *v58 = a->malloc(3*sizeof(void *));
  void *v59 = a->malloc(3*sizeof(void *));
  void *v60 = a->malloc(3*sizeof(void *));
  void *v61 = a->malloc(3*sizeof(void *));
  void *v62 = a->malloc(3*sizeof(void *));
  void *v63 = a->malloc(3*sizeof(void *));
  void *v64 = a->malloc(3*sizeof(void *));
  void *v65 = a->malloc(3*sizeof(void *));
  a->free(v50);
  a->free(v35);
  void *v66 = a->malloc(3*sizeof(void *));
  void *v67 = a->malloc(3*sizeof(void *));
  void *v68 = a->malloc(3*sizeof(void *));
  void *v69 = a->malloc(3*sizeof(void *));
  void *v70 = a->malloc(3*sizeof(void *));
  void *v71 = a->malloc(3*sizeof(void *));
  void *v72 = a->malloc(3*sizeof(void *));
  a->free(v57);
  void *v73 = a->malloc(3*sizeof(void *));
  a->free(v67);
  a->free(v34);
  a->free(v72);
  a->free(v61);
  a->free(v12);
  a->free(v17);
  void *v74 = a->malloc(3*sizeof(void *));
  void *v75 = a->malloc(3*sizeof(void *));
  a->free(v46);
  void *v76 = a->malloc(3*sizeof(void *));
  a->free(v56);
  void *v77 = a->malloc(3*sizeof(void *));
  a->free(v52);
  a->free(v21);
  a->free(v71);
  void *v78 = a->malloc(3*sizeof(void *));
  void *v79 = a->malloc(3*sizeof(void *));
  void *v80 = a->malloc(3*sizeof(void *));
  a->free(v65);
  void *v81 = a->malloc(3*sizeof(void *));
  void *v82 = a->malloc(3*sizeof(void *));
  void *v83 = a->malloc(3*sizeof(void *));
  a->free(v32);
  a->free(v49);
  a->free(v33);
  a->free(v48);
  a->free(v25);
  a->free(v83);
  a->free(v66);
  void *v84 = a->malloc(3*sizeof(void *));
  a->free(v29);
  a->free(v84);
  a->free(v55);
  void *v85 = a->malloc(3*sizeof(void *));
  void *v86 = a->malloc(3*sizeof(void *));
  a->free(v8);
  void *v87 = a->malloc(3*sizeof(void *));
  void *v88 = a->malloc(3*sizeof(void *));
  a->free(v79);
  a->free(v76);
  void *v89 = a->malloc(3*sizeof(void *));
  a->free(v14);
  a->free(v40);
  a->free(v38);
  a->free(v77);
  a->free(v43);
  a->free(v89);
  a->free(v81);
  void *v90 = a->malloc(3*sizeof(void *));
  void *v91 = a->malloc(3*sizeof(void *));
  a->free(v70);
  a->free(v47);
  a->free(v69);
  void *v92 = a->malloc(3*sizeof(void *));
  void *v93 = a->malloc(3*sizeof(void *));
  a->free(v60);
  a->free(v75);
  a->free(v93);
  a->free(v36);
  a->free(v87);
  a->free(v16);
  a->free(v80);
  void *v94 = a->malloc(3*sizeof(void *));
  void *v95 = a->malloc(3*sizeof(void *));
  void *v96 = a->malloc(3*sizeof(void *));
  a->free(v82);
  a->free(v59);
  a->free(v54);
  a->free(v94);
  a->free(v64);
  a->free(v73);
  a->free(v58);
  void *v97 = a->malloc(3*sizeof(void *));
  void *v98 = a->malloc(3*sizeof(void *));
  void *v99 = a->malloc(3*sizeof(void *));
  a->free(v45);
  void *v100 = a->malloc(3*sizeof(void *));
  void *v101 = a->malloc(3*sizeof(void *));
  void *v102 = a->malloc(3*sizeof(void *));
  void *v103 = a->malloc(3*sizeof(void *));
  a->free(v90);
  void *v104 = a->malloc(3*sizeof(void *));
  void *v105 = a->malloc(3*sizeof(void *));
  a->free(v102);
  a->free(v85);
  a->free(v68);
  a->free(v98);
  void *v106 = a->malloc(3*sizeof(void *));
  a->free(v103);
  a->free(v97);
  a->free(v100);
  a->free(v20);
  void *v107 = a->malloc(3*sizeof(void *));
  void *v108 = a->malloc(3*sizeof(void *));
  a->free(v96);
  a->free(v62);
  a->free(v15);
  a->free(v74);
  void *v109 = a->malloc(3*sizeof(void *));
  a->free(v86);
  a->free(v95);
  void *v110 = a->malloc(3*sizeof(void *));
  void *v111 = a->malloc(3*sizeof(void *));
  a->free(v107);
  void *v112 = a->malloc(3*sizeof(void *));
  a->free(v91);
  a->free(v110);
  a->free(v99);
  a->free(v78);
  void *v113 = a->malloc(3*sizeof(void *));
  a->free(v101);
  void *v114 = a->malloc(3*sizeof(void *));
  void *v115 = a->malloc(3*sizeof(void *));
  a->free(v104);
  a->free(v63);
  a->free(v105);
  void *v116 = a->malloc(3*sizeof(void *));
  a->free(v114);
  void *v117 = a->malloc(3*sizeof(void *));
  a->free(v51);
  void *v118 = a->malloc(3*sizeof(void *));
  a->free(v117);
  a->free(v115);
  void *v119 = a->malloc(3*sizeof(void *));
  a->free(v116);
  a->free(v106);
  a->free(v108);
  void *v120 = a->malloc(3*sizeof(void *));
  void *v121 = a->malloc(3*sizeof(void *));
  a->free(v88);
  void *v122 = a->malloc(3*sizeof(void *));
  void *v123 = a->malloc(3*sizeof(void *));
  a->free(v122);
  void *v124 = a->malloc(3*sizeof(void *));
  void *v125 = a->malloc(3*sizeof(void *));
  a->free(v109);
  a->free(v19);
  a->free(v113);
  void *v126 = a->malloc(3*sizeof(void *));
  a->free(v118);
  void *v127 = a->malloc(3*sizeof(void *));
  void *v128 = a->malloc(3*sizeof(void *));
  void *v129 = a->malloc(3*sizeof(void *));
  a->free(v111);
  void *v130 = a->malloc(3*sizeof(void *));
  a->free(v112);
  a->free(v126);
  a->free(v119);
  a->free(v127);
  void *v131 = a->malloc(3*sizeof(void *));
  a->free(v129);
  a->free(v130);
  void *v132 = a->malloc(3*sizeof(void *));
  a->free(v120);
  a->free(v132);
  a->free(v124);
  a->free(v92);
  a->free(v131);
  void *v133 = a->malloc(3*sizeof(void *));
  a->free(v125);
  a->free(v121);
  a->free(v128);
  a->free(v133);
  void *v134 = a->malloc(3*sizeof(void *));
  a->free(v134);
  void *v135 = a->malloc(3*sizeof(void *));
  a->free(v135);
  void *v136 = a->malloc(3*sizeof(void *));
  a->free(v123);
  a->free(v136);
  return 0;
}
